---
meta: # optional, ignored by tooling
  date: "2026-01-15"
  version: 1
  tags: ["base"]

defaults:
  repo: "teashellf"
  path: "dotfiles"
  required: true


links:
  - src: git
    dest: "$XDG_CONFIG_HOME/git"

  - src: shell/env.sh
    dest: "$XDG_CONFIG_HOME/teagarden/env.sh"

  - src: git/ignore
    dest: "$HOME/.vcs-ignore"

  - src: git/identities/private.conf
    dest: "$HOME/.gitidentity"

  - src: zsh/zshenv.zsh
    dest: "$HOME/.zshenv"

  - src: bash/profile.sh
    dest: "$HOME/.profile"

  - src: bash/bash_profile.sh
    dest: "$HOME/.bash_profile"

  - src: bash/bashrc
    dest: "$HOME/.bashrc"

  - src: zsh
    dest: "$XDG_CONFIG_HOME/zsh"

  - src: vim/vimrc
    dest: "$HOME/.vimrc"

  - src: kitty
    dest: "$XDG_CONFIG_HOME/kitty"

  - src: python/ptpython.config.py
    dest: "$XDG_CONFIG_HOME/ptpython/config.py"

  - src: lesskey
    dest: "$HOME/.lesskey"

ensure:
  dirs:
    - path: $XDG_CONFIG_HOME/teagarden
      mode: "0755"
    - path: $XDG_CONFIG_HOME/zsh
      mode: "0755"
    - path: $XDG_STATE_HOME/zsh
      mode: "0700"
    - path: $XDG_DATA_HOME/z
      mode: "0700"
    - path: $XDG_CONFIG_HOME/readline
      mode: "0755"
    - path: $HOME/.local/bin
      mode: "0755"
    - path: $HOME/bin
      mode: "0755"
  files:
    - path: $XDG_STATE_HOME/zsh/history
      mode: "0600"
    - path: $XDG_CONFIG_HOME/readline/inputrc
      mode: "0644"
